// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAca22jv3pCzTPVTDH21UU-f-tAlMseaX0',
    appId: '1:624798621609:web:e0aa9db26ff0c5b892aeb8',
    messagingSenderId: '624798621609',
    projectId: 'atsreviews-5afab',
    authDomain: 'atsreviews-5afab.firebaseapp.com',
    databaseURL: 'https://atsreviews-5afab-default-rtdb.firebaseio.com',
    storageBucket: 'atsreviews-5afab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXPiOD1in5tm_IAD-01BNPSEdBSWb7nIA',
    appId: '1:624798621609:android:7fe5322f4dbc13f892aeb8',
    messagingSenderId: '624798621609',
    projectId: 'atsreviews-5afab',
    databaseURL: 'https://atsreviews-5afab-default-rtdb.firebaseio.com',
    storageBucket: 'atsreviews-5afab.appspot.com',
  );
}
