name: alphatreeservice
version: 0.0.1
summary: AlphaTreeService
description: Buisness web site

confinement: strict
base: core18
grade: stable

slots:
  dbus-alphatreeservice-app:
    interface: dbus
    bus: session
    name: org.alphatreeservice

apps:
  alphatreeservice:
    command: alphatreeservice
    extensions: [flutter-master]
    plugs:
    - network

parts:
  alphatreeservice:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
